kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-rook-ceph
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph
